baseURL = ""
title = "Home"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Mike Jen"
    description = "Mike Jen's website"
    keywords = "blog,engineer,life"
    info = "Melbourne, Australia"
    avatarURL = "images/profile.png"
    
    footerContent = "Hello World!"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/www30127"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/chunlun/"
[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook"
    weight = 3
    url = "https://www.facebook.com/chunlun.jen"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "/about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "/blogs/"

            [[languages.en.menu.main]]
            name = "Experiences"
            weight = 3
            url = "/experiences/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 4
            url = "projects/"

    [languages.zh-tw]
        languageName = "中文"
        title = "主頁"

        [languages.zh-tw.params]
            author = "任俊倫"
            info = "墨爾本 澳大利亞"
            description = "任俊倫的網站"
            keywords = "部落格,工程師,生活"
            footerContent = "哈囉"

        [languages.zh-tw.menu]

            [[languages.zh-tw.menu.main]]
            name = "關於我"
            weight = 1
            url = "/about/"

            [[languages.zh-tw.menu.main]]
            name = "經歷"
            weight = 3
            url = "/experiences/"

            [[languages.zh-tw.menu.main]]
            name = "實作項目"
            weight = 4
            url = "/projects/"

